### ISSUE TITLE
Comment and cleanup of visualisation

### ISSUE THREAD

**Issue by naveenoid** [robotology-playground/mex-wholebodymodel#11]
The visualiser, especially the GUI components of run_forwardDyn and the graphics drawing components of visualize_forwardDyn need cleanup and commenting. Its currently filled with too much kludge.

Also possible bug with the new WBI ID but I am currently investigating this. Without cleanup its basically impossible for me to debug.

**Comment by barrelback** [comment]
visualizer code is cleaned and commented in https://github.com/robotology-playground/mex-wholebodymodel/commit/dda85770c5baf373dd989b3ccbeff0520ddb8b77 . 
I checked the forward dynamics and the controller (both the old and the new one) and there seems to be a problem. However it seems ok for zero torques. I'm not sure if it is related to the recent changes in this repo.
