### ISSUE TITLE
Assumptions on floating base position w.r.t. world reference frame

### ISSUE THREAD

**Issue by iron76** [robotology-playground/mex-wholebodymodel#14]
When computing the floating base mass matrix, the mex-wholebodymodel currently takes the joint-angles as input (https://github.com/robotology-playground/mex-wholebodymodel/blame/master/matlab-src/timeTest.m#L26). For a floating base system, the floating base mass matrix should be a function of the joint-angles and the floating base configuration. In the code the latter (i.e. the floating base configuration) is computed internally by assuming that the world to root rigid motion is known (https://github.com/robotology-playground/mex-wholebodymodel/blame/master/src/modelmassmatrix.cpp#L129-L132). In particular, it is assumed that the left foot reference corresponds to the world frame (https://github.com/robotology-playground/mex-wholebodymodel/blob/master/src/modelcomponent.cpp#L35-L45). This is an assumption that should be removed, especially since we already have other pieces of code that should not make this assumption (see for example the integration of forward dynamics by @barrelback).

**Comment by naveenoid** [comment]
Addressed in 2572fcb7937dd4bc6efc2ea0108f9f3def529ac3
