### ISSUE TITLE
wholeBodyModel initialization opens some YARP ports

### ISSUE THREAD

**Issue by iron76** [robotology-playground/mex-wholebodymodel#2]
Apparently the wholeBodyModel has still some YARP dependencies since when launching wholeBodyModel('model-initialise','icubGazeboSim'); I obtain the following messages on the shell where matlab was launched (yarserver running)

yarp: Port /wbiTestmodel/torso/rpc:o active at tcp://192.168.7.1:10002
yarp: Port /wbiTestmodel/torso/command:o active at tcp://192.168.7.1:10003
yarp: Port /wbiTestmodel/torso/state:i active at tcp://192.168.7.1:10004
Problems instantiating the device driver torso

If yarpserver is not running the test script timeTest.m crashes Matlab. If yarpserver is running everything goes smoothly.

**Comment by traversaro** [comment]
Fixed at higher level in https://github.com/robotology-playground/yarp-wholebodyinterface/commit/b78c3fe59cfdd4098a0da786f8ad43d8adb6b36c .
