### ISSUE TITLE
Matrix ordering 

### ISSUE THREAD

**Issue by francesco-romano** [robotology-playground/mex-wholebodymodel#21]
Matlab serialises matrices in Column Major ordering while wbi uses the Row major ordering.

Functions must take this issue in consideration (currently I think only the Jacobian computation is affected).

**Comment by DanielePucci** [comment]
Hi guys, did we fix this?

**Comment by DanielePucci** [comment]
I verify after some debugging: we did not.

**Comment by naveenoid** [comment]
Sorry missed this issue..fixing it by tonight.

---
Naveen Kuppuswamy, PhD
Post-doctoral Fellow,
Cognitive Humanoids Lab,
Department of Robotics, Brain and Cognitive Sciences (RBCS),
Istituto Italiano di Tecnologia, Genova, Italy

**Comment by naveenoid** [comment]
Would a temporary workaround in the wrapper wbm_jacobian  using reshape()' be sufficient for now? I can push a C++ solution properly.

**Comment by naveenoid** [comment]
8d884f32b84bac3d01b245397bdbd9cef55e874b
