### ISSUE TITLE
Proper error message if input vectors are given as rows instead of columns

### ISSUE THREAD

**Issue by DanielePucci** [robotology-playground/mex-wholebodymodel#22]
When using this interface, all vectors are assumed to be column vectors. So, if the user mistakenly passes a row vector, MATLAB complains with

~~~
Error using wholeBodyModel
Malformed state argument dimensions in ModelGeneralisedForces call
~~~

Probably, it would be better to add further information, so that to help the user recognize the error.

**Comment by naveenoid** [comment]
It is recommended that the matlab wrappers in whole-body-model functions be used. They will respond to a "help" command on matlab and include documentation on dimensions.
